### ISSUE TITLE
ol or ul style alignment problem

### ISSUE THREAD

**Issue by gtyhn** [daohoangson/flutter_widget_from_html#324] opened 2020-09-25 05:59 UTC
when using the ol or ul style, alignment problems occur with non-english characters.

![demo](https://user-images.githubusercontent.com/8544251/94231734-2eb32d00-ff37-11ea-911d-c429f753444b.png)

using Flutter_widget_from_HTML 0.5.0+5

**Comment by daohoangson** [comment] 2020-09-25 19:38
This appears to be an issue with East Asian languages where the character height is much higher than latin's. Can you share your specific HTML?

**Comment by gtyhn** [comment] 2020-09-26 03:52
@daohoangson 
thanks for your reply. this is my test code

```dart
import 'package:flutter/material.dart';
import 'package:flutter_widget_from_html/flutter_widget_from_html.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final _html =
      '<ul><li>hello汉字</li><li>hello2</li><li>hello3</li></ul><ol><li>hello汉字</li><li>hello2</li><li>hello3</li></ol>';

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('test'),
      ),
      body: HtmlWidget(
        _html,
        textStyle: TextStyle(fontSize: 16),
      ),
    );
  }
}

```

**Comment by gtyhn** [comment] 2020-09-29 03:44
@daohoangson 
 is there a temporary solution to this problem? is this caused by problems with baseline alignment?

**Comment by daohoangson** [comment] 2020-09-29 03:52
I have no workaround at the moment. The text height is calculated separately between the LI contents and the marker so they are not well aligned.

Fixing this may require a fairly large refactor, I'm still researching solutions for this.

**Comment by gtyhn** [comment] 2020-09-29 04:24
could you consider using Row for Numbers and text?

for example:

```dart
Row(
	textBaseline: TextBaseline.alphabetic,
	crossAxisAlignment: CrossAxisAlignment.baseline,
	children: [
	  Padding(
		padding: EdgeInsets.only(left: ??, right: ??),
		child: Text(
		  isNumber ? '$_number.' : '•',
		  style: style,
		  textAlign: TextAlign.center,
		),
	  ),
	  Expanded(
		child: RichText(
		  text: ....,
		),
	  ),
	],
)
```

**Comment by daohoangson** [comment] 2020-09-29 05:15
Using `Row` won't fix this unfortunately.

- If you do use `center`, the marker will be center-aligned when the LI contents have more than one line. Which is wrong.
- If you don't use `center`, the marker and LI contents will be misaligned (just like using `Stack`)

**Comment by gtyhn** [comment] 2020-09-29 07:45
i used a temporary solution to solve this problem, just to test the idea

```dart

meta.register(_LiStyle(this, meta).buildOp);


class _LiStyle {
  final HtmlWidgetArticleFactory wf;
  final BuildMetadata listMeta;

  final _itemMetas = <BuildMetadata>[];
  final _itemWidgets = <WidgetPlaceholder>[];

  BuildOp _itemOp;

  _LiStyle(this.wf, this.listMeta);

  BuildOp get buildOp {
    return BuildOp(
      isBlockElement: true,
      defaultStyles: (element) {
        final styles = {
          'list-style-type': element.localName == 'ol' ? 'decimal' : 'circle',
        };

        return styles;
      },
      onChild: (childMeta) {
        final e = childMeta.element;
        if (e.localName != 'li') return;
        if (e.parent != listMeta.element) return;

        _itemOp ??= BuildOp(
          onWidgets: (itemMeta, widgets) {
            final column = wf.buildColumnPlaceholder(itemMeta, widgets) ?? WidgetPlaceholder<BuildMetadata>(itemMeta);

            final i = _itemMetas.length;
            _itemMetas.add(itemMeta);
            _itemWidgets.add(column);
            return [column.wrapWith((c, w) => _buildItem(c, w, i))];
          },
        );

        childMeta.register(_itemOp);
      },
    );
  }

  Widget _buildItem(BuildContext context, Widget child, int i) {
    final meta = _itemMetas[i];
    final listStyleType = listMeta['list-style-type'];
    final markerIndex = 1 + i;
    final tsh = meta.tsb().build(context);

    final markerText = wf.getListStyleMarker(listStyleType, markerIndex);
    final markerSpan = _buildMarkerSpan(tsh, listStyleType, markerText);

    return Row(
      textBaseline: TextBaseline.alphabetic,
      crossAxisAlignment: CrossAxisAlignment.baseline,
      children: [
        Padding(
          padding: const EdgeInsets.symmetric(horizontal: 10),
          child: markerSpan,
        ),
        Expanded(
          child: child,
        ),
      ],
    );
  }

  Widget _buildMarkerSpan(TextStyleHtml tsh, String type, String text) {
    final style = tsh.styleWithHeight;

    if (type == 'decimal' && (text?.isNotEmpty == true)) return Text(text, style: style);
    return Text('•', style: style);
  }
}


```

snapshot

![bug1](https://user-images.githubusercontent.com/8544251/94528268-b9af6280-026a-11eb-834a-b1c7699248a5.png)

**Comment by daohoangson** [comment] 2020-09-30 02:11
I ran your row-based `BuildOp` without the `list-style-type` override and shorter LI contents:

<img src="https://user-images.githubusercontent.com/239336/94635295-81586480-02fc-11eb-9a3e-c7e9b4868b1d.png" width="300" />

As you can see, it has the same issue with stack-based rendering. I think the problem is harder to see in your previous screenshot because: (1) your LI contents only has East Asian characters and (2) they are all multilines.

Btw, I have had a viable workaround for this, will put up a demo soon and let you know.

**Comment by gtyhn** [comment] 2020-09-30 03:21
good job, my friend, waiting for your reply!

**Comment by daohoangson** [comment] 2020-09-30 20:48
It's working!

<img src="https://user-images.githubusercontent.com/239336/94737978-ebbee280-0398-11eb-9b7f-b0a0a0c37651.png" width="300" />

**Comment by gtyhn** [comment] 2020-10-04 04:31
thanks, it's perfect and ready to post to pub.dev.

**Comment by daohoangson** [comment] 2020-10-05 07:24
`v0.5.0+7` has been released with the fix for this. Please try upgrading and let me know if it works for you.

**Comment by gtyhn** [comment] 2020-10-05 09:42
it has passed the test, it works very well, thank you very much, it can be closed

**Closed** 2020-10-05 09:54 UTC
Labels: question
