### ISSUE TITLE
Embedded video won't play: Mixed content / Content served over HTTP blocked

### ISSUE THREAD

**Issue by ja2375** [daohoangson/flutter_widget_from_html#39] opened 2019-05-14 08:14 UTC
First of all, thank you for this amazing plugin. It is really useful.

I am trying to load a video embedded from a site that is wrongly configured. It loads everything over HTTPS except the video stream that loads over HTTP. I tried to load it over HTTPS but it just refuses the connection.
This is a bug from that site. But i think they won't be fixing it even if i tell them...

Anyway, when i load the iframe and try to play the video, it gives me this error:

`Mixed Content: The page at 'https://secure-embed.rtve.es/drmn/embed/video/2862002' was loaded over HTTPS, but requested an insecure video 'http://mvod2.lvlt.rtve.es/resources/TE_NGVA/mp4/9/1/1416137859019.mp4?nvb=20190514074656&nva=20190515064656&token=051aa169c77f851b8776e'. This request has been blocked; the content must be served over HTTPS.", source: https://secure-embed.rtve.es/drmn/embed/video/2862002 (0)`

and the video won't play. The player just stays static.

This is the embed code, so you can try it out if you want to:

`<iframe src="https://secure-embed.rtve.es/drmn/embed/video/2862002" name="Suesa, en femenino y plural" style="width:100%;height:90%;position:absolute;left:0;top:0;overflow:hidden;border:none;background-color:transparent;" scrolling="no" allowfullscreen="allowfullscreen"></iframe>`

I am going to try to write to them and tell them about this bug. But as i don't expect an answer from them, my question is: Is there any way i could allow the video to load over HTTP (allow the mixed content)?

Thanks in advance!

**Comment by daohoangson** [comment] 2019-05-14 08:47
There are 2 underlying issues here:

1. The official Flutter WebView plugin doesn't allow us to change the platform view directly <- this can be workaround.
2. Android WebView has an option to render mixed contents but the iOS one does not.

With both of these, I'm afraid there is not much I can do to help you with this. Sorry.

**Comment by ja2375** [comment] 2019-05-14 08:59
Thank you for the info. I will then cross my fingers hoping that they reply.

Thanks again!

**Comment by daohoangson** [comment] 2020-07-13 15:41
Because the root cause is outside of this package, I'm closing this issue now.

**Closed by daohoangson** 2020-07-13 15:41 UTC
Labels: wontfix

**Comment by CocoaJerry** [comment] 2021-12-29 08:44
请问，安卓上这个问题有解决方案么？
