### ISSUE TITLE
Non-breaking Space

### ISSUE THREAD

**Issue by egorges** [daohoangson/flutter_widget_from_html#185] opened 2020-05-18 20:06 UTC
Feature Request:
**& nbsp;** 
and also the corresponding handling of '**\u00A0**' (unicode non-breaking space) .

**Comment by daohoangson** [comment] 2020-05-19 00:55
Can you elaborate on what is **not** working as intended?

**Comment by egorges** [comment] 2020-05-19 01:00
Non-breaking space is used to keep continuous text together, so you can avoid formatting like:
```
xxxx longe text xxxx US$
1.00
```
and force it to format like
```
xxx long text xxxx
US$ 1.00

```
**nbsp** is HTML standard. It can be simulated with the unicode non-breaking space char: '\u00A0' , which should give the same result.

**Comment by daohoangson** [comment] 2020-05-19 01:27
Hmm, yeah. Let me see what can be done.

**Comment by daohoangson** [comment] 2020-05-19 06:06
I have just released `v0.3.3+4` with the fix for this. Can you try upgrading?

**Comment by egorges** [comment] 2020-05-19 15:45
> I have just released `v0.3.3+4` with the fix for this. Can you try upgrading?

Worked perfectly! Thanks a lot.

**Comment by daohoangson** [comment] 2020-05-19 16:50
Great to hear. I'm closing this issue for now.

**Closed** 2020-05-26 10:14 UTC
Labels: bug
