### ISSUE TITLE
Preload to improve performance

### ISSUE THREAD

**Issue by orestesgaolin** [daohoangson/flutter_widget_from_html#152] opened 2020-04-06 14:34 UTC
When navigating to a page that has HtmlWidget I encounter the lag. 

For instance the ripple on the button on the previous page stops and few frames are dropped during page transition.

Is there a way to preload the content of the HtmlWidget?

**Comment by daohoangson** [comment] 2020-04-06 14:38
Currently no. The widget does cache the built tree after the initial build though.

How big is your HTML? Are you running on a real device in release/profile mode or are you still testing in debug? I would like to receive the HTML and tweak the code for better performance if possible.

**Comment by orestesgaolin** [comment] 2020-04-06 15:06
> Currently no. The widget does cache the built tree after the initial build though.
> 
> How big is your HTML? Are you running on a real device in release/profile mode or are you still testing in debug? I would like to receive the HTML and tweak the code for better performance if possible.

Sure, I can send you the html privately. It's relatively large file and unfortunately it's generated by MS Word.

**Comment by daohoangson** [comment] 2020-04-06 15:12
Ah, Word generates incredibly complicated HTML. Please send the HTML to daohoangson at gmail dot com. I'll take a look, thank you.

**Comment by daohoangson** [comment] 2020-04-07 03:40
I have tested your 18KB file and it shows up pretty fast on my test app (release mode). Probably it is slower in your app because of all the real business logic etc. The performance also depends on the device (e.g. powerful device will be faster).

Anyway, I have a working PR that will render the HTML asynchronously. All heavy work is put on a different thread to avoid blocking the Flutter main thread. Are you comfortable with changing pubspec to a git branch and rebuild the app to test? I'll give detailed instruction if you want do try this new work-in-progress version.

**Comment by orestesgaolin** [comment] 2020-04-07 05:36
Sure, would love to test it!

Pozdrawiam,
Dominik Roszkowski

wt., 7 kwi 2020, 05:45 użytkownik Đào Hoàng Sơn <notifications@github.com>
napisał:

**Comment by daohoangson** [comment] 2020-04-07 10:04
Well, I have published a rc version for easy testing. Just update your `pubspec.yaml`:

```yaml
  flutter_widget_from_html: ^0.4.0-rc.2020040701
```

**Comment by orestesgaolin** [comment] 2020-04-07 15:13
Thanks, I can see a loader now and the navigation is much smoother. Is there any way to provide custom loader?

**Comment by orestesgaolin** [comment] 2020-04-07 15:14
Ok, I've just found that I can provide my own buildAsyncBuilder:

```dart
(BuildContext _, AsyncSnapshot<Widget> snapshot) =>
    snapshot.hasData
        ? snapshot.data
        : const Center(
            child: Padding(
            padding: EdgeInsets.all(8),
            child: CircularProgressIndicator(),
          ))
```

**Comment by daohoangson** [comment] 2020-04-07 15:21
Yes, that's the one 😆

**Comment by ercadev** [comment] 2020-04-29 09:09
What's status on this one?
I'm rendering pretty light html except for an iframe in every page. I experience that the UI freezes for a short second before the content is showing.

**Comment by orestesgaolin** [comment] 2020-04-29 09:19
I recommend to try newest prerelease. It works just fine in my app.

**Comment by daohoangson** [comment] 2020-04-29 09:20
@ercadev: the async build feature is pretty solid, it has been released in the 0.4.0 rc. Howerver, the UI freeze caused by web view is unrelated. It is slow because Flutter must use a platform view for that.

**Comment by ercadev** [comment] 2020-04-29 09:24
@orestesgaolin @daohoangson 
Thank you I'll try it. 
Can i please have documentation as mentioned earlier in this thread? Or how do I implement this?

>  I'll give detailed instruction if you want do try this new work-in-progress version.

**Comment by daohoangson** [comment] 2020-04-29 15:51
> update: it was pretty clear how to use it. Don't need any help

Yes, if you use the 0.4.0 rc, it will kick in automatically if the html is huge. But as I said, it won't make a difference in your use case because the web view is slow by itself...

**Closed** 2020-08-19 09:08 UTC
Labels: question
