### ISSUE TITLE
Select all only select one paragraph.

### ISSUE THREAD

**Issue by FiShelly** [daohoangson/flutter_widget_from_html#727] opened 2022-02-09 08:41 UTC
## Steps to Reproduce

<details>
  <summary>HTML</summary>

```html
<p>1</p>
<p>2</p>
```
</details>

<details>
  <summary>`HtmlWidget` configuration</summary>

```dart
HtmlWidget( html,
                         enableCaching: false,
                        isSelectable: true,)
```
</details>

<details>
  <summary>Tesing environment</summary>

```
[✓] Flutter (Channel stable, 2.8.1, on Mac OS X 10.14.6 18G95
    darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.8.1 at /Users/xiefucheng/flutter-source
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (8 weeks ago), 2021-12-16
      08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK
    version 31.0.0)
    • Android SDK at /Users/xiefucheng/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/xiefucheng/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ✗ Flutter requires a minimum Xcode version of 12.0.1.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google
      Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.10+0-b96-7281165)

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (2 available)
    • NOH AL00 (mobile) • 192.168.2.12:5555 • android-arm64  •
      Android 10 (API 29)
    • Chrome (web)      • chrome            • web-javascript •
      Google Chrome 98.0.4758.80

! Doctor found issues in 1 category.
```
</details>

## Expected results

select all can select all paragraph

## Actual results

select all only select one paragraph

**Comment by daohoangson** [comment] 2022-02-10 02:36
Thank you for reporting, this is a known limitation of the current implementation.

The HTML is broken down into smaller pieces depending on the markup so a document may be rendered as multiple `SelectableText` widgets. The "select all" option runs within a single selectable context so it doesn't work very well. Dragging selection across paragraphs is also affected and has the same root cause.

**Comment by daohoangson** [comment] 2022-05-25 02:23
This has just been merged https://github.com/flutter/flutter/pull/95226, hopefully we can test it soon.

**Comment by FiShelly** [comment] 2022-05-25 07:11
> This has just been merged [flutter/flutter#95226](https://github.com/flutter/flutter/pull/95226), hopefully we can test it soon.

Yes, i see it. but maybe it will effect in flutter3?  My app is not going to be updated flutter version at this time~ so has any other plan？

**Comment by daohoangson** [comment] 2022-05-25 07:49
Very unlikely. This is a rather large refactor within Flutter framework itself, porting it from v3 to v2.10 will be difficult.

**Comment by FiShelly** [comment] 2022-05-25 08:20
ok, i know, thx so much~

**Closed** 2022-12-25 14:47 UTC
Labels: question
