### ISSUE TITLE
align justify compact to subscript 

### ISSUE THREAD

**Issue by SCTech100** [daohoangson/flutter_widget_from_html#314] opened 2020-09-14 07:00 UTC
the subscript or superscript in html will not adjust the text beautifully with justify alignment
ex: (long text) 10^7 (long text) ... with justify alignment
the 7 will be on the left from 10 
how to solve this..

**Comment by daohoangson** [comment] 2020-09-14 07:12
Can you share the HTML and preferably a screenshot?

**Comment by SCTech100** [comment] 2020-09-14 07:24
![Uploading Screenshot_2020-09-14-13-57-03-518_id.sch.kanaan.kiss.png…]()

**Comment by SCTech100** [comment] 2020-09-14 07:25
![Screenshot_2020-09-14-13-57-03-518_id sch kanaan kiss](https://user-images.githubusercontent.com/65840043/93056069-1705ba00-f696-11ea-832b-d3ca8b8c05e5.png)

**Comment by SCTech100** [comment] 2020-09-14 07:27
<p style="margin-left:8px; text-align:justify"><span><span><span>Sebuah kawat tembaga dengan luas penampang 2 mm<sup>2 </sup>memiliki modulus young 1,2 x 10<sup>10 </sup>N/m<sup>2</sup>. Kawat direnggangkan dengan gaya 160 N. jika panjang mula-mula kawat 50 cm, berapakah pertambahan panjang kawatnya?</span></span></span></p>

**Comment by SCTech100** [comment] 2020-09-14 07:28
html = '<p style="margin-left:8px; text-align:justify"><span><span><span>Sebuah kawat tembaga dengan luas penampang 2 mm<sup>2 </sup>memiliki modulus young 1,2 x 10<sup>10 </sup>N/m<sup>2</sup>. Kawat direnggangkan dengan gaya 160 N. jika panjang mula-mula kawat 50 cm, berapakah pertambahan panjang kawatnya?</span></span></span></p>'

**Comment by SCTech100** [comment] 2020-09-14 07:29
![image](https://user-images.githubusercontent.com/65840043/93056487-af03a380-f696-11ea-89c8-7cb2e32a232a.png)

**Comment by daohoangson** [comment] 2020-09-14 09:37
This looks like a Flutter bug. I have created a simple reproduce and reported here https://github.com/flutter/flutter/issues/50009#issuecomment-691940825.

**Comment by SCTech100** [comment] 2020-09-14 09:56
oh i see.. thank you very much for the comment sir

**Comment by daohoangson** [comment] 2021-02-10 03:55
Apparently this has been fixed in https://github.com/flutter/engine/pull/24219, need to revalidate.

**Comment by daohoangson** [comment] 2021-09-11 18:09
This was a long time ago but it looks good now, I'm closing.

| | | |
| --- | --- | --- |
| <img width="787" alt="Screen Shot 2021-09-12 at 01 08 15" src="https://user-images.githubusercontent.com/239336/132957208-a312c5c0-deff-49f0-bcdb-9f2da496f7bb.png"> | <img width="649" alt="Screen Shot 2021-09-12 at 01 08 25" src="https://user-images.githubusercontent.com/239336/132957210-eff406f7-fa4f-47fc-a999-ce87352234c7.png"> | <img width="427" alt="Screen Shot 2021-09-12 at 01 08 30" src="https://user-images.githubusercontent.com/239336/132957213-8364f41d-8e0c-4ba6-b61d-4cf337df6245.png"> |

**Closed by daohoangson** 2021-09-11 18:09 UTC
Labels: question
