### ISSUE TITLE
paragraph Spacing

### ISSUE THREAD

**Issue by thenexus00** [daohoangson/flutter_widget_from_html#30] opened 2019-04-23 03:51 UTC
Using the latest version of this or core the Paragraphs do not have any spacing below them so the content just comes out as one big chunk of text regardless.

**Comment by daohoangson** [comment] 2019-04-23 04:42
Can you share your html for me to reproduce?

**Comment by daohoangson** [comment] 2019-04-24 02:31
Ah, I think I understand now.

Did you reset `Config.textPadding`? Normally there is a default padding for all text block. Anyway, I have added an additional bottom margin of 1em for P tag. It will be included in the next release.

**Comment by daohoangson** [comment] 2019-05-02 02:05
v0.2.0 has been released with the fix for this.

**Comment by daohoangson** [comment] 2019-05-09 18:49
I'm closing this issue due to inactivity.

**Closed by daohoangson** 2019-05-09 18:49 UTC
Labels: bug
