### ISSUE TITLE
Error building apk

### ISSUE THREAD

**Issue by dannycortesv** [daohoangson/flutter_widget_from_html#82] opened 2019-09-24 19:09 UTC
Hi thanks for this plugin, it is great! I'm gettting this error using the latest version when compiling on android:

Users/dannycortesv/Desktop/go/app/android/app/src/main/AndroidManifest.xml:22:18-86 Error:
        Attribute application@appComponentFactory value=(androidx.core.app.CoreComponentFactory) from [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86
        is also present at [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91 value=(android.support.v4.app.CoreComponentFactory).
        Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:9:5-32:19 to override.
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:processReleaseManifest'.                
> Manifest merger failed : Attribute application@appComponentFactory value=(androidx.core.app.CoreComponentFactory) from [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86
        is also present at [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91 value=(android.support.v4.app.CoreComponentFactory).
        Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:9:5-32:19 to override.

**Comment by daohoangson** [comment] 2019-09-25 02:20
It looks like your app is using Android X but one of the plugins/libraries are still using the deprecated support lib. You encountered this error after adding `flutter_widget_from_html` into `pubspec.yaml`?

**Comment by dannycortesv** [comment] 2019-09-25 02:26
Thanks for your help @daohoangson, it was working fine last week, but today it is not working, if i remove  _flutter_widget_from_html_ from _pubspec.yaml_ it generates the apk properly. Also, I'm not using AndroidX.

**Comment by daohoangson** [comment] 2019-09-25 02:33
Please open `Terminal` and `cd` into the android library inside your Flutter project tree and run this command `./gradlew app:dependencies`. It will list the dependencies for your app. Copy and paste the list here and I'll try to pin point the issue.

**Comment by dannycortesv** [comment] 2019-09-25 02:50
Ok sure here the list: 

https://dl.dropboxusercontent.com/s/x5sfjvb2fm9rnr1/output

**Comment by daohoangson** [comment] 2019-09-25 05:24
That's weird. I see support lib but no Android X in the dependencies. Can
you share your `pubspec.yaml` and `AndroidManifest.xml`?

**Comment by daohoangson** [comment] 2019-09-25 07:42
Just FYI, here is the output for the [https://github.com/daohoangson/flutter_widget_from_html/tree/master/packages/example](example app): https://gist.github.com/daohoangson/94a51980d2fc42f445e6885d8e75da9f. Notice that there is no `support-compat` references. 

Looks like you have some flutter_embedding dependency that uses the old support lib?

**Comment by dannycortesv** [comment] 2019-09-25 11:44
Hi @daohoangson, yes sure here my files:

https://dl.dropboxusercontent.com/s/nlhsmjsn1qsxxhx/pubspec.yaml

https://dl.dropboxusercontent.com/s/n0dp9fc2ccprc1w/AndroidManifest.xml

**Comment by dannycortesv** [comment] 2019-09-25 12:00
I just created a new default project, then built an apk succesfully (without any plugin), then added flutter_widget_from_html (just it, no other plugin), there i got the error, so seems that the issue is related with latest updates?

**Comment by daohoangson** [comment] 2019-09-25 12:13
Oh, what is your flutter version? `flutter doctor -v` output should be
useful.

**Comment by dannycortesv** [comment] 2019-09-25 12:15
I'm using: Flutter 1.10.6-pre.39 • channel master 

<img width="731" alt="Screen Shot 2019-09-25 at 7 14 27 AM" src="https://user-images.githubusercontent.com/367137/65599809-4a6ea680-df64-11e9-9d48-318ecb83947f.png">

**Comment by daohoangson** [comment] 2019-09-25 12:38
I'm on stable. Let me switch to master and see whether I can reproduce
your problem.

**Comment by daohoangson** [comment] 2019-09-25 14:58
It is confirmed, switching to latest master and I encountered exactly the same issue.

I have also tracked it down to this PR https://github.com/flutter/flutter/pull/39157 which is being reverted / re-landed by Flutter developers (which means it is not working as intended). I would not recommend using master channel for your app under normal circumstances. At least use beta channel if you want to live on the edge 👍

**Comment by dannycortesv** [comment] 2019-09-25 15:12
Ok @daohoangson , thanks for your help!

**Closed** 2019-09-26 03:03 UTC
Labels: wontfix

**Comment by hasankaraman** [comment] 2020-01-09 23:36
I could not solve this error. Can you help with this.

**Comment by daohoangson** [comment] 2020-01-10 01:31
@hasankaraman please create a new issue with your specific error e.g. full output when you run `flutter build apk`.
