### ISSUE TITLE
 assert(indexOf != -1)

### ISSUE THREAD

**Issue by dvzhou** [daohoangson/flutter_widget_from_html#159] opened 2020-04-13 07:20 UTC
data_classes.dart 451line  assert(indexOf != -1) is not true

**Comment by daohoangson** [comment] 2020-04-13 07:47
Sorry for the problem, can you share your HTML that is triggering this bug?

**Comment by dvzhou** [comment] 2020-04-13 08:21
this is the HTML words

"<p style="
	margin: 0 pt 0 pt 0.0001 pt;text - align: justify;font - family: 'Times New Roman';font - size: 10.5 pt;
	"><span class="
	10 " style="
	font - family: 宋体;font - weight: normal;font - size: 10.5000 pt;
	">VB</span><sub><span class="
	10 " style="
	font - family: 宋体;font - weight: normal;font - size: 10.5000 pt;vertical - align: sub;
	">2</span></sub><span class="
	10 " style="
	font - family: 宋体;font - weight: normal;font - size: 10.5000 pt;
	"><span style="
	font - family: 宋体;
	">极发生的电极反应为：</span>2VB</span><sub><span class="
	10 " style="
	font - family: 宋体;font - weight: normal;font - size: 10.5000 pt;vertical - align: sub;
	">2</span></sub><span class="
	10 " style="
	font - family: 宋体;font - weight: normal;font - size: 10.5000 pt;
	"> +22OH</span><sup><span class="
	10 " style="
	font - family: 宋体;font - weight: normal;font - size: 10.5000 pt;vertical - align: super;
	">—</span></sup><span class="
	10 " style="
	font - family: 宋体;font - weight: normal;font - size: 10.5000 pt;
	">—22e</span><sup><span class="
	10 " style="
	font - family: 宋体;font - weight: normal;font - size: 10.5000 pt;vertical - align: super;
	">-</span></sup><span class="
	10 " style="
	font - family: 宋体;font - weight: normal;font - size: 10.5000 pt;
	"> = V</span><sub><span class="
	10 " style="
	font - family: 宋体;font - weight: normal;font - size: 10.5000 pt;vertical - align: sub;
	">2</span></sub><span class="
	10 " style="
	font - family: 宋体;font - weight: normal;font - size: 10.5000 pt;
	">O</span><sub><span class="
	10 " style="
	font - family: 宋体;font - weight: normal;font - size: 10.5000 pt;vertical - align: sub;
	">5 </span></sub><span class="
	10 " style="
	font - family: 宋体;font - weight: normal;font - size: 10.5000 pt;
	">+ 2B</span><sub><span class="
	10 " style="
	font - family: 宋体;font - weight: normal;font - size: 10.5000 pt;vertical - align: sub;
	">2</span></sub><span class="
	10 " style="
	font - family: 宋体;font - weight: normal;font - size: 10.5000 pt;
	">O</span><sub><span class="
	10 " style="
	font - family: 宋体;font - weight: normal;font - size: 10.5000 pt;vertical - align: sub;
	">3</span></sub><span class="
	10 " style="
	font - family: 宋体;font - weight: normal;font - size: 10.5000 pt;
	"> + 11H</span><sub><span class="
	10 " style="
	font - family: 宋体;font - weight: normal;font - size: 10.5000 pt;vertical - align: sub;
	">2</span></sub><span class="
	10 " style="
	font - family: 宋体;font - weight: normal;font - size: 10.5000 pt;
	">O</span></p>"

**Comment by dvzhou** [comment] 2020-04-13 08:28
another question 
![Uploading WechatIMG3600.png…]()
The numbers in the chemical equation don't show completely
the html is 
[html.txt](https://github.com/daohoangson/flutter_widget_from_html/files/4468703/html.txt)

Thank you for your answer first

**Comment by daohoangson** [comment] 2020-04-14 03:15
I can confirm this bug in the latest version (`0.3.3`). However there is a pre-release version which doesn't have this bug. Can you update your pubspec to use `0.4.0-rc.2020040701` and try again?

**Comment by dvzhou** [comment] 2020-04-14 03:34
> I can confirm this bug in the latest version (`0.3.3`). However there is a pre-release version which doesn't have this bug. Can you update your pubspec to use `0.4.0-rc.2020040701` and try again?

Sorry, when I tried to change the version as you said, there was a new problem, so I can't verify whether the above problem has been modified.
![1586834926499](https://user-images.githubusercontent.com/40446804/79183367-ddf5bf00-7e43-11ea-8827-006c5a7755a2.jpg)

**Comment by daohoangson** [comment] 2020-04-15 03:20
Weird, I'm testing with both HTMLs uploaded above with `0.4.0-rc.2020040701` and it renders without issue. Can you double check?

| 1 | 2 |
| --- | --- |
| ![Simulator Screen Shot - iPhone 11 - 2020-04-15 at 10 18 04](https://user-images.githubusercontent.com/239336/79295282-810d0e00-7f02-11ea-99a8-615a5e3482b8.png) | ![Simulator Screen Shot - iPhone 11 - 2020-04-15 at 10 17 35](https://user-images.githubusercontent.com/239336/79295293-8407fe80-7f02-11ea-8f47-051b0ce17111.png) |

> but the number corner in the chemical equation is not correct.

Can you elaborate on this? With screenshot maybe?

**Comment by dvzhou** [comment] 2020-04-15 06:54
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-04-15 at 14 34 35](https://user-images.githubusercontent.com/40446804/79306864-87ae7c00-7f28-11ea-9afc-b25e2b69c038.png)
The picture above shows the display effect when I use version 0.3.2+2
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-04-15 at 14 48 18](https://user-images.githubusercontent.com/40446804/79306929-a6147780-7f28-11ea-8216-bd793baf9496.png)
The picture above shows the display effect when I use version 0.4.0-rc.2020040701
<img width="992" alt="WX20200415-144913@2x" src="https://user-images.githubusercontent.com/40446804/79306975-b88eb100-7f28-11ea-827a-14926667134f.png">
When I use version 0.4.0-rc.2020040701, the error message in the figure above will appear

Of course, this page has other HTML besides the previous HTML, but there is a problem with this HTML. I don't know if it matters.

**Comment by daohoangson** [comment] 2020-04-15 07:41
Ah, sub script is not supported before 0.3.3 so that's why it didn't work for you. For the 0.4.0-rc, you probably encountered some bug. Can you share the full HTML so I can reproduce and fix it?

**Comment by dvzhou** [comment] 2020-04-15 08:06
[json.txt](https://github.com/daohoangson/flutter_widget_from_html/files/4479840/json.txt)
This is the JSON string of complete data. I need to display them all on one page.
thanks a lot.

**Comment by daohoangson** [comment] 2020-04-16 03:49
I have found the problematic HTML, this bit:

```html
<p><sub><code>\\n  \\n\\n\\n</code></sub></p>
```

As an immediate workaround, you can try to remove that from the input string. I'll release a patch version with the fix later today.

**Comment by dvzhou** [comment] 2020-04-16 06:33
OK, thank you for your patient feedback these days. Thank you very much.

**Comment by daohoangson** [comment] 2020-04-16 07:17
Good news! Version `0.4.0-rc.2020041601` has been released with the fix. It should render your HTML without issue now, see this screen recording:

[![Alt text](https://img.youtube.com/vi/qkdSpKNsz-8/0.jpg)](https://www.youtube.com/watch?v=qkdSpKNsz-8)

**Comment by dvzhou** [comment] 2020-04-16 07:43
Perfect! Solved my big problem, thank you perfectly.

**Comment by daohoangson** [comment] 2020-04-16 10:32
Awesome. Since your issue has been resolved. I'm closing this now.

**Closed by daohoangson** 2020-04-16 10:32 UTC
Labels: bug

**Comment by dvzhou** [comment] 2020-04-29 04:02
Sorry, in version 0.3.3, the problem still exists.
