### ISSUE TITLE
FwfhTextStyle doesn't support incomplete TextStyle

### ISSUE THREAD

**Issue by teoprayoga** [daohoangson/flutter_widget_from_html#698] opened 2021-12-23 04:06 UTC
htmlwidget 0.8.4 not working on debug mode, but working on release mode (ios and android)

FwfhTextStyle.from() doesn't support incomplete TextStyle. Use `DefaultTextStyle.of(context)` to obtain the current style.
'package:fwfh_text_style/fwfh_text_style.dart':
Failed assertion: line 168 pos 11: 'ref.inherit == false'

## Steps to Reproduce

```html
<p>Dengan menekan <b>Registrasi</b>, Saya setuju dengan <a href='#' style='color:#000'>Ketentuan Layanan</a> dan <a href='#' style='color:#000'>Kebijakan Privasi</a> </p>
```

```dart
                              HtmlWidget(
                                Get.deviceLocale == const Locale('in')
                                    ? privacyId
                                    : privacyEn,
                                onTapUrl: (p0) async {
                                  if (await canLaunch(p0)) {
                                    await launch(p0);
                                    return true;
                                  }
                                  Get.snackbar(
                                      'warning'.tr,
                                      'cant_launch_name'.trParams({
                                        'name': 'URL',
                                      }));
                                  return false;
                                },
                              ),
```

**Comment by DFelten** [comment] 2021-12-27 08:11
Same issue here when using the HTMLWidget on a page with a `CupertinoPageScaffold` instead of a normal Scaffold (We're using `flutter_platform_widgets` and there the `PlatformScaffold` is using the `CupertinoPageScaffold` for iOS.

```dart
class TestPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return const CupertinoPageScaffold(
      child: TMXHtmlWidget(
        html: '<p>test</p>',
      ),
    );
  }
}
```

**Comment by peter100u** [comment] 2022-01-04 02:27
FwfhTextStyle doesn't support incomplete TextStyle

**Comment by hpoul** [comment] 2022-01-17 21:10
stumbled upon this error with flutter 2.8.1 and fwfh_text_style 2.7.2 with flutter_widget_from_html_core 0.8.4 - is there any workaround? 🤔️ @daohoangson 

```
======== Exception caught by widgets library =======================================================
The following assertion was thrown building ColumnPlaceholder(BuildMetadata(<root></root>), dirty, dependencies: [TshWidget]):
FwfhTextStyle.from() doesn't support incomplete TextStyle. Use `DefaultTextStyle.of(context)` to obtain the current style.
'package:fwfh_text_style/fwfh_text_style.dart':
Failed assertion: line 168 pos 11: 'ref.inherit == false'

The relevant error-causing widget was: 
  HtmlWidget HtmlWidget:file:///Users/herbert/dev/hbh/hbh_app/lib/ui/screens/content.dart:225:14
When the exception was thrown, this was the stack: 
#2      new _TextStyleProxy._ (package:fwfh_text_style/fwfh_text_style.dart:168:11)
#3      new FwfhTextStyle.from (package:fwfh_text_style/fwfh_text_style.dart:14:15)
#4      new TextStyleHtml.root (package:flutter_widget_from_html_core/src/data/text_style.dart:35:27)
#5      _RootTsb.builder (package:flutter_widget_from_html_core/src/core_html_widget.dart:262:36)
#6      TextStyleBuilder.build (package:flutter_widget_from_html_core/src/data/text_style.dart:139:24)
#7      _RootTsb.build (package:flutter_widget_from_html_core/src/core_html_widget.dart:254:18)
#8      ColumnPlaceholder.build (package:flutter_widget_from_html_core/src/internal/ops/column.dart:21:26)
#9      StatelessElement.build (package:flutter/src/widgets/framework.dart:4662:28)
#10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4588:15)
#11     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#12     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4566:5)
#13     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4561:5)
...     Normal element mounting (18 frames)
#31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3631:14)
#32     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6261:36)
#33     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6272:32)
...     Normal element mounting (94 frames)
#127    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3631:14)
#128    Element.updateChild (package:flutter/src/widgets/framework.dart:3380:20)
#129    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#130    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#131    StatelessElement.update (package:flutter/src/widgets/framework.dart:4669:5)
#132    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#133    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#134    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#135    ProxyElement.update (package:flutter/src/widgets/framework.dart:4943:5)
#136    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#137    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#138    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#139    ProxyElement.update (package:flutter/src/widgets/framework.dart:4943:5)
#140    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#141    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5626:32)
#142    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6284:17)
#143    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#144    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#145    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
#146    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#147    StatefulElement.update (package:flutter/src/widgets/framework.dart:4795:5)
#148    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#149    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#150    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#151    ProxyElement.update (package:flutter/src/widgets/framework.dart:4943:5)
#152    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#153    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#154    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
#155    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#156    StatefulElement.update (package:flutter/src/widgets/framework.dart:4795:5)
#157    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#158    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6130:14)
#159    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#160    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#161    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#162    StatelessElement.update (package:flutter/src/widgets/framework.dart:4669:5)
#163    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#164    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6130:14)
#165    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#166    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#167    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
#168    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#169    StatefulElement.update (package:flutter/src/widgets/framework.dart:4795:5)
#170    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#171    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#172    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
#173    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#174    StatefulElement.update (package:flutter/src/widgets/framework.dart:4795:5)
#175    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#176    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#177    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#178    ProxyElement.update (package:flutter/src/widgets/framework.dart:4943:5)
#179    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#180    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#181    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#182    StatelessElement.update (package:flutter/src/widgets/framework.dart:4669:5)
#183    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#184    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#185    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
#186    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#187    StatefulElement.update (package:flutter/src/widgets/framework.dart:4795:5)
#188    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#189    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#190    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#191    ProxyElement.update (package:flutter/src/widgets/framework.dart:4943:5)
#192    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#193    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#194    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
#195    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#196    StatefulElement.update (package:flutter/src/widgets/framework.dart:4795:5)
#197    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#198    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#199    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
#200    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#201    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2578:33)
#202    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
#203    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#204    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1145:15)
#205    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
#206    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
#210    _invoke (dart:ui/hooks.dart:150:10)
#211    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
#212    _drawFrame (dart:ui/hooks.dart:114:31)
(elided 5 frames from class _AssertionError and dart:async)
```

**Comment by daohoangson** [comment] 2022-01-18 06:59
I'm still investigating this. Do you use `MaterialApp` and/or `Scaffold` in your app?

**Comment by hpoul** [comment] 2022-01-18 07:25
> Do you use `MaterialApp` and/or `Scaffold` in your app

Yes, both.. so you couldn't yet reproduce the problem?

Btw, i don't quite understand the need for the asset. What errors can we expect in production if ref.inherit is false?

**Comment by daohoangson** [comment] 2022-01-18 09:08
In order to allow resetting the font height, this package has to use a subclass of `TextStyle` which may cause error if `inherit == true`...

**Comment by AristideNestor** [comment] 2022-01-28 10:19
Any fix for this ? : ) I'm also using Cupertino with Material App

**Comment by daohoangson** [comment] 2022-01-28 11:47
You meant `CupertinoPageScaffold` @AristideNestor ?

**Comment by AristideNestor** [comment] 2022-01-28 11:51
Yes I'm using both Material App & Cupertino with `CupertinoPageScaffold`

**Comment by daohoangson** [comment] 2022-01-28 12:03
Ah, finally. I was testing with `CupertinoPageScaffold` inside a `CupertinoApp` and couldn't find any issue. Turned out it happens if `CupertinoPageScaffold` is used with `MaterialApp`...

**Comment by hpoul** [comment] 2022-01-29 10:23
I don't think this has **anything** to do with `CupertinoPageScaffold` .. I did a `flutter create fwfh_test` (with flutter 2.8.1) and just replaced the `MyHomePage` widget with the following code:

```
class MyHomePage extends StatelessWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return HtmlWidget('<p>Lorem Ipsum</p>');
  }
}
```

the result:
<img width="564" alt="Screen Shot 2022-01-29 at 10 20 44" src="https://user-images.githubusercontent.com/313066/151657277-8ba185fc-5e5c-40f1-9879-49c4b4affc36.png">

<details>
<summary>here is the whole main.dart</summary>

```
import 'package:flutter/material.dart';
import 'package:flutter_widget_from_html/flutter_widget_from_html.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return HtmlWidget('<p>Lorem Ipsum</p>');
  }
}
```

</details>

**Comment by daohoangson** [comment] 2022-01-30 03:10
Yes, the text style requirement is too strict is the root cause. I'm releasing a new version to relax the assert today.

**Comment by daohoangson** [comment] 2022-01-30 03:29
A new version of `fwfh_text_style` has been released. Please try it out by upgrading the dependency `flutter pub upgrade fwfh_text_style`.

**Comment by hpoul** [comment] 2022-01-30 05:11
Thanks, at least it's working now in debug mode as well. But it would be nice if it would not completely spam my debug log.. I've got a handful of widgets on a page and it makes it completely unusable.. and it's really not like it is any special case... 
It's just a [MaterialApp with the HtmlWidget](https://github.com/daohoangson/flutter_widget_from_html/issues/698#issuecomment-1024883709).. i can't see how anybody manages not to trigger that assert?

**Comment by daohoangson** [comment] 2022-01-30 06:59
You have `HtmlWidget` directly under `MaterialApp` in your real app? Without `Scaffold` etc.?

**Comment by hpoul** [comment] 2022-01-30 08:32
No, in my real app i am using a material `Scaffold`. But it's easily reproduced.. simply setting a theme with a typography:

```dart
class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        typography: Typography.material2018(platform: defaultTargetPlatform),
      ),
      title: 'Flutter Demo',
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(body: HtmlWidget('<p>Lorem Ipsum</p>'));
  }
}
```

it seems like a completely valid use case, to use `material2018` typography 🤔️

**Comment by daohoangson** [comment] 2022-01-31 04:12
A new version is available which is less noisy. Please try `flutter pub upgrade fwfh_text_style` in your app @hpoul.

**Comment by hpoul** [comment] 2022-02-12 07:30
@daohoangson I'm now getting the following assertion error, couldn't yet easily reproduce it though:

```
======== Exception caught by widgets library =======================================================
The following assertion was thrown building ColumnPlaceholder(BuildMetadata(<root></root>), dirty, dependencies: [TshWidget]):
The text style should be modified by methods of the existing instance: apply(), copyWith() or merge().
'package:flutter_widget_from_html_core/src/data/text_style.dart':
Failed assertion: line 61 pos 7: 'style is FwfhTextStyle?'

The relevant error-causing widget was: 
  HtmlWidget HtmlWidget:file:///Users/herbert/dev/hbh/hbh_app/lib/ui/screens/content.dart:268:14
When the exception was thrown, this was the stack: 
#2      TextStyleHtml.copyWith (package:flutter_widget_from_html_core/src/data/text_style.dart:61:7)
#3      TextStyleOps.fontSizeEm (package:flutter_widget_from_html_core/src/internal/ops/text_style.dart:56:67)
#4      TextStyleBuilder.build (package:flutter_widget_from_html_core/src/data/text_style.dart:139:24)
#5      WidgetFactory.flatten.<anonymous closure> (package:flutter_widget_from_html_core/src/core_widget_factory.dart:398:32)
#6      WidgetPlaceholder.callBuilders (package:flutter_widget_from_html_core/src/core_helpers.dart:185:38)
#7      WidgetPlaceholder.build (package:flutter_widget_from_html_core/src/core_helpers.dart:174:41)
#8      WidgetPlaceholder.unwrap (package:flutter_widget_from_html_core/src/core_helpers.dart:229:23)
#9      ColumnPlaceholder._buildWidgets.<anonymous closure> (package:flutter_widget_from_html_core/src/internal/ops/column.dart:52:43)
#10     MappedIterator.moveNext (dart:_internal/iterable.dart:391:20)
#11     WhereIterator.moveNext (dart:_internal/iterable.dart:438:22)
#12     ColumnPlaceholder._buildWidgets (package:flutter_widget_from_html_core/src/internal/ops/column.dart:55:25)
#13     ColumnPlaceholder.build (package:flutter_widget_from_html_core/src/internal/ops/column.dart:22:21)
#14     StatelessElement.build (package:flutter/src/widgets/framework.dart:4827:28)
#15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4754:15)
#16     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#17     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735:5)
#18     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729:5)
...     Normal element mounting (18 frames)
#36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790:14)
#37     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6422:36)
#38     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6433:32)
...     Normal element mounting (73 frames)
#111    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790:14)
#112    Element.updateChild (package:flutter/src/widgets/framework.dart:3524:20)
#113    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#114    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#115    StatelessElement.update (package:flutter/src/widgets/framework.dart:4834:5)
#116    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#117    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#118    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#119    ProxyElement.update (package:flutter/src/widgets/framework.dart:5108:5)
#120    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#121    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#122    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#123    ProxyElement.update (package:flutter/src/widgets/framework.dart:5108:5)
#124    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#125    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5787:32)
#126    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6445:17)
#127    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#128    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#129    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#130    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#131    StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#132    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#133    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#134    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#135    ProxyElement.update (package:flutter/src/widgets/framework.dart:5108:5)
#136    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#137    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#138    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#139    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#140    StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#141    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#142    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6291:14)
#143    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#144    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#145    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#146    StatelessElement.update (package:flutter/src/widgets/framework.dart:4834:5)
#147    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#148    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6291:14)
#149    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#150    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#151    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#152    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#153    StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#154    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#155    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#156    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#157    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#158    StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#159    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#160    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#161    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#162    ProxyElement.update (package:flutter/src/widgets/framework.dart:5108:5)
#163    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#164    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#165    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#166    StatelessElement.update (package:flutter/src/widgets/framework.dart:4834:5)
#167    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#168    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#169    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#170    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#171    StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#172    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#173    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#174    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#175    ProxyElement.update (package:flutter/src/widgets/framework.dart:5108:5)
#176    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#177    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#178    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#179    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#180    StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#181    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#182    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#183    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#184    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#185    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2659:19)
#186    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
#187    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#188    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#189    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1081:9)
#190    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:995:5)
#194    _invoke (dart:ui/hooks.dart:151:10)
#195    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#196    _drawFrame (dart:ui/hooks.dart:115:31)
(elided 5 frames from class _AssertionError and dart:async)
```

**Comment by daohoangson** [comment] 2022-02-12 08:50
The assert statement has been removed. Make sure you are running the latest version of the package.

**Closed** 2022-05-01 07:34 UTC
Labels: question
