### ISSUE TITLE
iframe problem

### ISSUE THREAD

**Issue by AliveDevs** [daohoangson/flutter_widget_from_html#823] opened 2022-09-20 03:45 UTC
My code

` HtmlWidget(
        '''<p align="center"><iframe src="https://music.163.com/outchain/player?type=2&amp;id=22003184&amp;auto=0&amp;height=66" width="330" height="86"></iframe></p>''',
      )`

Result: only show the src text

is a bug? or some option need to set

**Comment by daohoangson** [comment] 2022-09-20 03:47
Which package are you using? `flutter_widget_from_html` or `flutter_widget_from_html_core`?

**Comment by AliveDevs** [comment] 2022-09-21 01:42
> Which package are you using? `flutter_widget_from_html` or `flutter_widget_from_html_core`?

env:

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.2, on macOS 12.3 21E230 darwin-x64, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Android Studio (version 2021.2)
[✓] Connected device (1 available)
[✓] HTTP Host Availability

• No issues found!

dependency

` 
  flutter_widget_from_html: ^0.8.5`

**Comment by Akshit792** [comment] 2022-09-28 03:48
hey there, i have attached a picture of the mobile screenshot in which if you see i'm basically rendering the html body of a mail and showing it up on the screen. if you see in the screenshot there is a green button with keep my account text on it on clicking that button it should take the user to the link which is in the html body but it isn't doing it. can you please help me in this.


HtmlWidget(
                    mail!.emails![index].bodyHtml!,
                    isSelectable: true,
                    onTapUrl: (url) async {
                      print(url);
                      if (isStringValid(url) &&
                          await canLaunchUrl(Uri.parse(url))) {
                        await launchUrl(
                          Uri.parse(url),
                          mode: LaunchMode.externalApplication,
                        );
                        return true;
                      } else {
                        throw 'Could not launch $url';
                      }
                    },
                    onTapImage: (imageData) {
                      print('image is tapped');
                    },
                    onErrorBuilder: (context, element, error) =>
                        Text('$element error: $error'),
                    onLoadingBuilder: (context, element, loadingProgress) =>
                        Center(
                            child: Container(
                                width: 15,
                                height: 15,
                                child: CircularProgressIndicator(
                                  strokeWidth: 1.5,
                                ))),
                    renderMode: RenderMode.column,
                    textStyle: TextStyle(
                      fontSize: 14,
                    ),
                    factoryBuilder: () => _MyFactory(),
                    buildAsync: true,
                  ),
                  
![Screenshot_20220927-191258_TW-Dev (1)](https://user-images.githubusercontent.com/92843323/192544166-7ae16e26-51fc-45f9-ae85-18c0adb7f018.jpg)
![Screenshot_20220927-191258_TW-Dev (1)](https://user-images.githubusercontent.com/92843323/192544223-2b609a06-1485-4aee-890c-cbac5f631685.jpg)

**Comment by daohoangson** [comment] 2022-12-25 14:41
I'm closing this as it's a duplicate of https://github.com/daohoangson/flutter_widget_from_html/issues/824

**Closed by daohoangson** 2022-12-25 14:41 UTC
Labels: duplicate
