### ISSUE TITLE
[fwfh_text_style: 2.13.0] Error: No named parameter with the name 'fontVariations'

### ISSUE THREAD

**Issue by dJani97** [daohoangson/flutter_widget_from_html#804] opened 2022-07-31 21:59 UTC
## Steps to Reproduce

My project depends on `better_player: ^0.0.83`, which depends on `fwfh_text_style`. So currently `fwfh_text_style: 2.13.0` is getting pulled in as a transitive dependency.

I get the following error while building for Android:

    ../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/fwfh_text_style-2.13.0/lib/fwfh_text_style.dart:98:11: Error: No named parameter with the name 'fontVariations'.
              fontVariations: fontVariations,
              ^^^^^^^^^^^^^^
    ../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/fwfh_text_style-2.13.0/lib/fwfh_text_style.dart:164:9: Error: No named parameter with the name 'fontVariations'.
            fontVariations: fontVariations ?? this.fontVariations,
            ^^^^^^^^^^^^^^
    /C:/Apps/flutter/packages/flutter/lib/src/painting/text_style.dart:468:9: Context: Found this candidate, but the arguments don't match.
      const TextStyle({
            ^^^^^^^^^
    ../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/fwfh_text_style-2.13.0/lib/fwfh_text_style.dart:244:53: Error: The getter 'fontVariations' isn't defined for the class 'TextStyle'.
     - 'TextStyle' is from 'package:flutter/src/painting/text_style.dart' ('/C:/Apps/flutter/packages/flutter/lib/src/painting/text_style.dart').
    Try correcting the name to the name of an existing getter, or defining a getter or field named 'fontVariations'.
      List<ui.FontVariation>? get fontVariations => ref.fontVariations;
                                                        ^^^^^^^^^^^^^^

To fix this issue, I had to specify the previous version (`fwfh_text_style: 2.7.3+1`) in my pubspec.yaml as a direct dependency. So I suspect there is a problem with the latest release.

Relevant Flutter doctor output:
[√] Flutter (Channel stable, 3.0.4, on Microsoft Windows [Version 10.0.22000.795], locale hu-HU)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Android Studio (version 2021.2)

**Comment by daohoangson** [comment] 2022-08-01 01:46
This is a duplicate of #803, I'm closing this for now.

**Closed by daohoangson** 2022-08-01 01:46 UTC
Labels: duplicate
