### ISSUE TITLE
Rendering Issue

### ISSUE THREAD

**Issue by Dulajdeshan** [daohoangson/flutter_widget_from_html#358] opened 2020-10-31 06:28 UTC
`
════════ Exception caught by rendering library ═════════════════════════════════════════════════════
Intrinsics are not available for PlaceholderAlignment.baseline, PlaceholderAlignment.aboveBaseline, or PlaceholderAlignment.belowBaseline,
'package:flutter/src/rendering/paragraph.dart':
Failed assertion: line 353 pos 18: 'RenderObject.debugCheckingIntrinsics'
The relevant error-causing widget was: 
  HtmlWidget file:///F:/Flutter%20Development/----/lib/views/post/post_view.dart:244:14`

**Comment by daohoangson** [comment] 2020-10-31 14:22
Can you share your HTML at the time of this error? Also, what is your Flutter version and package version?

**Comment by Dulajdeshan** [comment] 2020-11-01 03:21
`<p>A chance encounter at Cook Childrens Medical Center is all it took to set Todd Barrow on his mission to revamp classic country with his signature modern twist. One day, an American Idol contestant was slated to perform for the patients at Todd’s place of employment, but the audio tech was nowhere to be found. When he heard the call, Can anybody here run sound? Todd answered. In walked Texas Music Hall of Fame Honoree Sonny Burgess just as Todd was setting up the live rig, and the two musicians struck up a conversation. Sonny told Todd about his work with Charlie Pride and Randy Travis, and asked Todd if he might lend his technical skills to help build the recording studio sponsored by Garth Brooks and Troy Aikman he that had in the works. This serendipitous encounter yielded a coffee meeting to review the blueprints for the project, and before long, Sonny was meeting Todd for coffee weekly to discuss music. Eventually, he became Todds mentor, forever changing the course of Todds career.</p>\n<div>\n<p><strong>Additional Artist/Song Information:</strong></p>\n<p>Artist Name: Todd Barrow w/Jenn Ford<br />\nSong Title: Fun In Mexico<br />\nPublishing: Todd Barrow Music Publishing<br />\nPublishing Affiliation: BMI<br />\nAlbum Title: Fun In Mexico<br />\nRecord Label: Todd Barrow Music</p>\n</div>\n<div>\n<table style=\"width: 100%;\">\n<tbody>\n<tr style=\"text-align: center;\">\n<td style=\"width: 10%;\"><a href=\"https://toddbarrow.com/\"><img src=\"https://airplayaccess.com/aa_email_images/website-email.png\" height=\"40\" /></a></td>\n<td style=\"width: 10%;\"><a href=\"https://www.facebook.com/ToddBarrowMusic\"><img src=\"https://airplayaccess.com/aa_email_images/facebook-email.png\" height=\"40\" /></a></td>\n<td style=\"width: 10%;\"><a href=\"https://twitter.com/ToddBarrowMusic\"><img src=\"https://airplayaccess.com/aa_email_images/twitter-email.png\" height=\"40\" /></a></td>\n<td style=\"width: 10%;\"><a href=\"https://www.instagram.com/ToddBarrowMusic1/\"><img src=\"https://airplayaccess.com/aa_email_images/instagram-email.png\" height=\"40\" /></a></td>\n<td style=\"width: 10%;\"><a href=\"https://soundcloud.com/ToddBarrowMusic\"><img src=\"https://airplayaccess.com/aa_email_images/soundcloud-email.png\" height=\"40\" /></a></td>\n<td style=\"width: 10%;\"><a href=\"https://www.reverbnation.com/ToddBarrowMusic\"><img src=\"https://airplayaccess.com/aa_email_images/reverbnation-email.png\" height=\"40\" /></a></td>\n<td style=\"width: 10%;\"><a href=\"https://www.youtube.com/c/ToddBarrow\"><img src=\"https://airplayaccess.com/aa_email_images/youtube-email.png\" height=\"40\" /></a></td>\n<td style=\"width: 10%;\"><a href=\"https://open.spotify.com/album/53d7TCK8cJM5SnkGIDuuTb?si=CHljb1VBTna8l2Z-9CLS2g://www.spotify.com\"><img src=\"https://airplayaccess.com/aa_email_images/spotify-email.png\" height=\"40\" /></a></td>\n<td style=\"width: 10%;\"><a href=\"https://www.linkedin.com/in/ToddBarrowMusic\"><img src=\"https://airplayaccess.com/aa_email_images/linkedin-email.png\" height=\"40\" /></a></td>\n<td style=\"width: 10%;\"><a href=\"https://www.pinterest.com/toddbarrowmusic/_saved/\"><img src=\"https://airplayaccess.com/aa_email_images/pinterest-email.png\" height=\"40\" /></a></td>\n<td style=\"width: 0%;\"></td>\n</tr>\n</tbody>\n</table>\n</div>\n<div>\n<table style=\"width: 100%; font-size: 10pt; font-family: verdana;\">\n<tbody>\n<tr>\n<td>Radio Promotion:</td>\n</tr>\n<tr>\n<td>ShowBizz</td>\n</tr>\n<tr>\n<td>Geert Hakze</td>\n</tr>\n<tr>\n<td>Geerthakze@outlook.com</td>\n</tr>\n<tr>\n<td></td>\n</tr>\n<tr>\n<td>Publicity/PR:</td>\n</tr>\n<tr>\n<td>Phoenix PR</td>\n</tr>\n<tr>\n<td>Christy Michelle</td>\n</tr>\n<tr>\n<td>cmichelle@phoenixspark.com</td>\n</tr>\n<tr>\n<td>Booking Agent:</td>\n</tr>\n<tr>\n<td>Phoenix PR</td>\n</tr>\n<tr>\n<td>Christy Michelle</td>\n</tr>\n<tr>\n<td>cmichelle@phoenixspark.com</td>\n</tr>\n</tbody>\n</table>\n</div>\n<div>\n<div style=\"text-align: center;\"><a href=\"https://spinstrackingsystem.com/login/\" target=\"_blank\" rel=\"noopener noreferrer\"> <img src=\"https://airplayaccess.com/aa_email_images/apo_available_now.png\" alt=\"\" width=\"570\" height=\"auto\" /> </a></div>\n</div>\n<div id=\"themify_builder_content-8978\" class=\"themify_builder_content themify_builder_content-8978 themify_builder tf_clear\" data-postid=\"8978\"></div>\n<p><!-- /themify_builder_content --></p>\n<div id=\"themify_builder_content-368749\" data-postid=\"368749\" class=\"themify_builder_content themify_builder_content-368749 themify_builder tf_clear\">\n    </div>\n<!-- /themify_builder_content -->\n`

**Comment by daohoangson** [comment] 2020-11-03 09:30
`v0.5.1+4` has been released which should fix your issue. Please try updating and see whether it works. Thank you very much.

**Comment by misterfourtytwo** [comment] 2020-11-05 11:41
> `v0.5.1+4` has been released which should fix your issue. Please try updating and see whether it works. Thank you very much.

still aint working sometimes
example - image in the table
```[html]
<table>
    <tbody>
        <tr>
            <td style="text-align: center;">
                <img src="https://www.slivki.by/ximage/1602592366_%D1%8E%D0%BE%D0%BD%D0%B0%D0%BA%D0%B2%D0%B0.jpg">
            </td>
        </tr>
    </tbody>
</table>
```

**Comment by daohoangson** [comment] 2020-11-05 16:27
For TABLE, we have an open issue for its rewrite #346. And actually an in progress PR #365. I expect this will be completed soon.

**Comment by misterfourtytwo** [comment] 2020-11-06 09:39
the problem it works without text-align here so i thought u would like buggy behavior to be reported

**Comment by daohoangson** [comment] 2020-11-07 10:05
Of course, thank you the the report. The issue is kept open and I'll update this once the PR is merged.

**Comment by daohoangson** [comment] 2021-02-15 17:41
Version `0.5.2` has been released with the new TABLE implementation. Please try upgrading and let me know if it works for you. Thank you.

**Closed** 2021-05-30 09:33 UTC
Labels: question
