### ISSUE TITLE
[Bug] Screen lock however video is playing in tag <video>, iframe in android can't zoom and in iOS show popup

### ISSUE THREAD

**Issue by RathaIct** [daohoangson/flutter_widget_from_html#417] opened 2021-01-19 09:40 UTC
`<video controls>
        <source src="#" type="video/mp4">
        <source src="#" type="video/ogg">
    </video>`

**Comment by daohoangson** [comment] 2021-06-18 16:41
> Screen lock however video is playing in tag <video>

This looks like a bug with the video player. We are using another package for that so it's not really something I can fix. This has been reported for quite a while, I assume said bug should be fixed by now though. Please try again if you are still having this issue.

> iframe in android can't zoom and in iOS show popup

These sound like two separate issues. Without actual HTML to look at, I'm closing this now. Please open new separate issues for these. This repo now has issue templates, it helps to include as much info as possible to reproduce a bug.

**Closed by daohoangson** 2021-06-18 16:41 UTC
